# Generated by Django 2.2.3 on 2019-07-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fightcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, db_column='Index', null=True)),
                ('weight_class', models.TextField(blank=True, db_column='Weight Class', null=True)),
                ('winner', models.TextField(blank=True, db_column='Winner', null=True)),
                ('def_field', models.TextField(blank=True, db_column='def', null=True)),
                ('loser', models.TextField(blank=True, db_column='Loser', null=True)),
                ('won_by', models.TextField(blank=True, db_column='Won By', null=True)),
                ('round', models.TextField(blank=True, db_column='Round', null=True)),
                ('time', models.TextField(blank=True, db_column='Time', null=True)),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True)),
                ('card', models.TextField(blank=True, db_column='Card', null=True)),
            ],
            options={
                'db_table': 'fightcard',
                'managed': False,
            },
        ),
    ]
