# Generated by Django 2.2.3 on 2019-08-02 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_fightcard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'managed': False},
        ),
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.AddField(
            model_name='question',
            name='polls_question',
            field=models.CharField(db_column='Winner', default='', max_length=200),
            preserve_default=False,
        ),
    ]
