# Generated by Django 2.2.3 on 2019-08-02 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190802_0016'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='choice',
            table='polls_choice',
        ),
    ]
