# Generated by Django 2.2.3 on 2019-08-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190802_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='polls_wonBy',
            field=models.CharField(blank=True, db_column='WonBy', max_length=200),
        ),
    ]
