# Generated by Django 2.2.3 on 2019-08-02 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_question_polls_wonby'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'managed': False},
        ),
    ]
